name: CMake

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies 
        run: sudo apt-get install -y cmake make llvm-dev lld clang libclang-dev
      - name: Checkout Enzyme
        uses: actions/checkout@v3 
        with:
          repository: 'EnzymeAD/Enzyme'
          path: 'enzyme'
          ref: v0.0.81
      - name: cmake
        working-directory: enzyme
        run: mkdir build && cmake ../enzyme -DLLVM_EXTERNAL_LIT=`which lit` -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DLLVM_DIR=/usr/lib/llvm-${{ matrix.llvm }}/lib/cmake/llvm
      - name: make
        working-directory: enzyme/build
        run: make -j `nproc` LLVMEnzyme-${{ matrix.llvm }} ClangEnzyme-${{ matrix.llvm }} LLDEnzyme-${{ matrix.llvm }}        
      - name: Install Enzyme
        working-directory: enzyme/build
        run: make install
      - name: Checkout
        uses: actions/checkout@v3    
        with:
          path: 'main'
      - name: Configure
        working-directory: ./main
        run: mkdir build && cd build && cmake ..
      - name: Build
        working-directory: ./main
        run: make
      
