# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout spack
        uses: actions/checkout@v3 
        with:
          repository: 'spack/spack'
          path: '~/spack'
          ref: releases/v0.20
      - name: Debug
        run:  ls ~/spack
      - name: Install spack
        run:  . ~/spack/share/spack/setup-env.sh
      - name: Checkout
        uses: actions/checkout@v3      
      - name: Install dependencies
        run: |
          spack env load .
          spack install
      - name: Configure
        run: mkdir build && cd build && cmake ..
      - name: Build
        run: make
      
