# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout spack
        uses: actions/checkout@v3 
        with:
          repository: 'spack/spack'
          path: 'spack'
          ref: releases/v0.20
      - name: Install spack
        run: |
          source ./spack/share/spack/setup-env.sh
          spack env load ./main
          spack install
      - name: Checkout
        uses: actions/checkout@v3    
        with:
          path: 'main'
      - name: Install dependencies
        working-directory: ./main
        run: |
          spack env load .
          spack install
      - name: Configure
        working-directory: ./main
        run: mkdir build && cd build && cmake ..
      - name: Build
        working-directory: ./main
        run: make
      
